### ISSUE TITLE
Invalid US-ASCII ???

### ISSUE THREAD

**Issue by zenkbaries** [Kanna727/jekyll-run#15]
**Describe the bug**
When I hit "Jekyll Run", it reports this error: 

```
 "/Users/xxxxxxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-sass-converter-
1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid US-ASCII 
character "\\xE2" on line 6 (Jekyll::Converters::Scss::SyntaxError)
```
It suggests me to "bundle install" which I did and it didn't solve anything.

**To Reproduce**
1. While you are in Jekyll project, click on "Jekyll Run" (in the status bar at bottom of the screen)
4. The error shows up after it starts to build.

**Expected behavior**
I expect it to run "bundle exec Jekyll serve" and open the browser to display the Jekyll created site.

**Screenshots**
![Screen Shot 2020-09-07 at 8 08 14 PM](https://user-images.githubusercontent.com/8967420/92426091-3b1d4480-f146-11ea-89a4-de90c5503f40.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Catalina v. 10.15.5
 - Browser Chrome Version 85.0.4183.8
 - VS Code Version: 1.48.2
       
**Additional context**
I have googled it and tried many solutions they offered with similar error (if not an exactly the same error). Still not working.

**Comment by Kanna727** [comment]
Have you tried running `jekyll bundle exec serve` manually in terminal?

From the error message I can infer that your local code encoding is not UTF-8, Refer to this [issue](https://github.com/jekyll/jekyll/issues/4268) to resolve your encoding issue.

This extension just executes the `jekyll bundle exec serve` command. It cannot handle any error that can occur while bundling your site using Jekyll. So it just shows the error and exits.

**Comment by zenkbaries** [comment]
i can manually `bundle exec jekyll serve` in terminal in VS Code. executing it using your extension produce that code.

I did check this issue (https://github.com/jekyll/jekyll/issues/4268) and it didn't solve for me. I just couldn't pinpoint exactly what after I debug this.

**Comment by Kanna727** [comment]
In near future I'll release an update to generate logs for this extension. I'll notify you once I release the update, then you can share me the logs and I'll resolve this.

Meanwhile could you please provide me following details:

- Terminal output on executing `bundle exec jekyll serve` manually,
- Your installed version details of Ruby & Jekyll

**Comment by fusco** [comment]
Hi, 
Same error that @zenkbaries 

Version 
```
Mac os Big Sur. 11.0.1
Xcode  12.0 beta 6 
vscode : 1.51.1
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

Jekyll-run settings with 
``` --livereload --verbose --trace``` 

zsh locale : 

```shell                                                                
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"
```


if I run manually the Jekyll Run command in the vscode terminal or iterm, it's work perfectly.

If i compare the two outputs, I can view that Jekyll-run stop this before the `writing` sequance, just after `Pre-render / rendering`

<img width="514" alt="Capture d’écran 2020-11-12 à 17 09 55" src="https://user-images.githubusercontent.com/162724/98965113-f200bc80-2509-11eb-86ee-c337aae93fc8.png">


Of course, `bundle install`command don't resolve the problem.

**Comment by Kanna727** [comment]
I'm really sorry but I don't have access to any mac currently. I've tried to reproduce this on windows but in vain. Anyway I'll investigate this further as much as I can. I'm currently working on adding logs to this extension so that logs for this error can be sent from your side. Please wait for further notification from me. Thanks😊

**Comment by fusco** [comment]
Hi thanks for your answer. Strangely it work.

What happen since my post....
I have just rebooting my mac after an os update. 

Since the reboot, that's run perfectly.

Why ? I don't know. 
I have the same result for the differents tests post in my last comment.

If i can make something for help you, it's with pleasure
