### ISSUE TITLE
Support for command line flags?

### ISSUE THREAD

**Issue by Nishnha** [Kanna727/jekyll-run#16]
**Is your feature request related to a problem? Please describe.**
A way to add in command line flags for Jekyll. For example, a way to pass in the `--incremental` flag so Jekyll doesn't rebuild the output each run.

**Describe the solution you'd like**
A textbox in the extension settings to pass in the flags in as plain text (e.g. `--no-watch`)

**Describe alternatives you've considered**
A checkbox for each flag that can be set. Not preferable since there are many flags.

**Additional context**
It would probably be easiest to add this feature on the VS Code "Extension Setting" page

**Comment by Kanna727** [comment]
Hi @Nishnha,

Thanks for your feature request. I will definitely go with textbox in `Extension Settings` page.
