### ISSUE TITLE
Jekyll run thinks port 4000 is occupied

### ISSUE THREAD

**Issue by plenaerts** [Kanna727/jekyll-run#29]
Jekyll run shows the message "Port 4000 is already occupied by process: XYZ Either kill that process or use another port in _config.yml" when clicking the jekyll-run button with a jekyll repo opened.

PID XYZ is the virus software on my laptop, but it's not occupying that port. Running "bundle exec jekyll s" from WSL or powershell in the jekyll project dir serves the site perfectly fine on port 4000.

Changing the port in the plugin config does not seem to change the error. In the screenshot below I changed to 3000, restarted vs code, opened a file in the jekyll repo and clicked the jekyll run button.

![afbeelding](https://user-images.githubusercontent.com/14309550/99807528-edf32100-2b3f-11eb-87bb-45e9a1befb90.png)

Running versions:
![afbeelding](https://user-images.githubusercontent.com/14309550/99807817-4f1af480-2b40-11eb-86f1-a55be7589546.png)

Please let me know what kind of info I can add and how to investigate.

**Comment by Kanna727** [comment]
I'm sorry for the issue being auto closed. I've been busy in the past few months. I'll look into and provide a fix as soon as I can.

**Comment by Yukigamine** [comment]
I've noticed the same error. I can run `bundle exec jekyll serve` and then the plugin picks up that the server is running and will let me control it. But starting the server using the plugin fails.

Thanks!

**Comment by phil-harmoniq** [comment]
I've noticed this happens after I hit the stop button on the bottom bar. Even if I change the port, the plugin thinks the port is occupied. 🤔

**Comment by Yukigamine** [comment]
This is still an issue; just making sure the bot doesn't close.

**Comment by Yukigamine** [comment]
pls no close

**Comment by vivi90** [comment]
Bug still exists.. :-(

**Comment by alexiscreuzot** [comment]
I'm still encountering the issue

**Comment by jaewoo-so** [comment]
I'm still encountering the issue too

**Comment by dghassan98** [comment]
same issue here, any fix?

**Comment by Jearil** [comment]
still encountering the issue.. not sure if I can really use this plugin without this

**Comment by DannieBGoode** [comment]
issue still exists, unfortunately this plugin is useless if this is not fixed
