### ISSUE TITLE
Stops after "Jekyll Building..."

### ISSUE THREAD

**Issue by Jwiggiff** [Kanna727/jekyll-run#30]
**Describe the bug**
I have a Jekyll project setup. When I click Jekyll Run in the output window it stops after "Jekyll Building..."

**To Reproduce**
1. Create jekyll site with `jekyll new test-login --blank`
2. Click `Jekyll Run`
3. See error

**Expected behavior**
I expect to have the same output as running Jekyll Serve in the terminal. It builds and opens the site in browser.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
It works fine if I run `jekyll serve -l` in the terminal window.

**Comment by Kanna727** [comment]
I'm sorry for the issue being auto closed. I've been busy in the past few months. I'll look into and provide a fix as soon as I can.

**Comment by me-nkr** [comment]
Is this issue fixed?

**Comment by bacloud22** [comment]
no on windows.
