### ISSUE TITLE
Add support for Jekyll files being in a sub-directory

### ISSUE THREAD

**Issue by normanr** [Kanna727/jekyll-run#31]
**Is your feature request related to a problem? Please describe.**
In one of my workspaces I have the Jekyll files in a sub-directory. The extension doesn't work unless I open the sub-directory as its own workspace. I'd like it to work without having to do that.

**Describe the solution you'd like**
The extension should auto-detect the location of `_config.yml` and pass that as the source directory (`-s`) to Jekyll.

**Describe alternatives you've considered**
The sub-directory location could just be an extension setting. This might even be required if there are multiple `_config.yml` files in a workspace.

**Additional context**
Just adding a `-s` argument to `commandLineArguments` doesn't work because `_config.yml` is assumed to be directly in `workspaceFolder` (and not a sub-directory), also `commandLineArguments` are only passed to `jekyll serve`, not `jekyll build`.

**Comment by normanr** [comment]
ack stale, but would still be nice to fix

**Comment by Kanna727** [comment]
I'm sorry for the issue being marked stale. I've been busy in the past few months. I'll look into and provide a fix as soon as I can.

**Comment by rafaelurben** [comment]
+1 This would indeed be great, because passing `-s SUBFOLDER` as `jekyll-run.commandLineArguments` doesn't work.

**Comment by rafaelurben** [comment]
I think this shouldn't be marked as stale.

**Comment by normanr** [comment]
ack stale, but would still be nice to fix

**Comment by chriskyfung** [comment]
@normanr Please refer to #46
