### ISSUE TITLE
please support github codespaces

### ISSUE THREAD

**Issue by amir-arad** [Kanna727/jekyll-run#33]
I'm trying to configure github codespaces for my jekyll project, but I get a `"Either the workspace/folder: <my workspace name> is not Jekyll compatible or the opened file is not part of the Jekyll folder"`

**Comment by Kanna727** [comment]
I currently don't have access to github codespaces, I've requested for early access though. Until then I'm working on adding logs to this extension. Once I release that I'll let you know and you can share me the logs to help

**Comment by amir-arad** [comment]
Thank you.

Codespaces is basically a hosted service that you can mimic locally. 
It uses remote development (the `devcontainer.json` feature) to define the development environment, which you can run on any machine. whatever works there should work at codespaces.

[have a look](https://code.visualstudio.com/docs/remote/codespaces#_extension-authors)

as a side note I think it's a genious feature and it's extremely easy to use. saves me setting up jekyll environment in my local machine.
