### ISSUE TITLE
Point the extension at a subdirectory in the vscode folder

### ISSUE THREAD

**Issue by jeremy9959** [Kanna727/jekyll-run#46]
In working on a GitHub repo I often have jekyll build the documentation in a subdirectory.  Currently jekyll-run
executes ```bundle exec jekyll serve``` in the vscode directory so I can't just call jekyll-run -- it doesn't find the jekyll info. 

It would be great if you could add a configuration option so that you can specify the directory in which bundle exec jekyll serve
gets run.

**Comment by chriskyfung** [comment]
@jeremy9959 A simple way to solve is by moving your `_config.yml`, `Gemfile`, and `Gemfile.lock` to the root of your vscode directory. Then, add `source : ./subdir` in the `config.yml`.
