### ISSUE TITLE
Mac/Linux file separator

### ISSUE THREAD

**Issue by choru-k** [Kanna727/jekyll-run#8]
**Describe the bug**
In mac and linux, this extension cannot find `_config.yaml` file.
As you know in `checkConfigAndGetPort` use `\` as file separator. 
But linux and mac use `/`. So you need to check double or check os.

**To Reproduce**
1. In the mac or linux, run extenstion

**Comment by Kanna727** [comment]
Thanks for finding out this issue. Working on a fix
